AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A lambda for sending monthly cloud-spend emails for STRIDES accounts

Parameters:
  ScheduleExpression:
    Type: String
    Description: Schedule expressions using cron
    Default: cron(30 10 2 * ? *)

  MinimumValue:
    Type: String
    Description: 'Minimum total to send an email. Default: $0.01'
    Default: '0.01'
    AllowedPattern: '^\d+(\.\d+)?$'
    ConstraintDescription: 'must be a floating point number'

  Sender:
    Type: String
    Description: Sender email address

  Recipients:
    Type: String
    Description: Comma-separated list of email recipients

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

Resources:
#lambda execution role config
  MonthlyServicesUsageLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: 'LambdaSSMAssume'
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Statement:
            - Action:
                 - "ce:Describe*"
                 - "ce:Get*"
                 - "ce:List*"
                 - "logs:CreateLogGroup"
                 - "logs:CreateLogStream"
                 - "logs:DescribeLogStreams"
                 - "logs:PutLogEvents"
                 - "ses:SendEmail"
              Resource: "*"
              Effect: Allow

#This Lambda Function will fetch Billing details for AWS linked Account and will send it over mail.
  MonthlyServicesUsage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: email_strides/app.lambda_handler
      CodeUri: .
      Runtime: python3.11
      MemorySize: 128
      Role: !GetAtt MonthlyServicesUsageLambdaRole.Arn
      Environment:
        Variables:
          SENDER: !Ref Sender
          RECIPIENTS: !Ref Recipients
          MINIMUM: !Ref MinimumValue
      Events:
        ScheduledEventTrigger:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MonthlyServicesUsage
      Principal: 'events.amazonaws.com'

Outputs:
  MonthlyServicesUsageFunctionArn:
    Description: "MonthlyServicesUsage Lambda Function ARN"
    Value: !GetAtt MonthlyServicesUsage.Arn
  MonthlyServicesUsageFunctionRoleArn:
    Description: "IAM Role created for MonthlyServicesUsage function"
    Value: !GetAtt MonthlyServicesUsageLambdaRole.Arn
